name: Web production build and publish

on: workflow_dispatch


jobs:
  publishdocker:
    name: "Build docker and publish to ECR"
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Build, tag, and push image to Amazon ECR
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
