name: Web production build and publish

on: workflow_dispatch


jobs:
  publishdocker:
    name: "Build docker and publish to ECR"
    runs-on: ubuntu-latest
    
    steps:
    - name: Check if triggered from a tag
      run: |
        if [ "${{ github.ref_type }}" = "branch" ]; then
          echo"Workflow not triggered from a tag, stopping workflow. Triggering from a tag is necessary to give the docker image the right version, before publishing it to Amazon ECR."
          exit 78
        fi
      shell: bash
    - name: Check out code
      uses: actions/checkout@v3
    - name: Build, tag, and push image to Amazon ECR
      env: 
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        echo $IMAGE_TAG
